# Generated by Django 3.2.24 on 2024-11-02 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='donate_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.CharField(max_length=100)),
                ('NEEDS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.needs_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
    ]
