# Generated by Django 3.2.24 on 2024-11-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_donate_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_table',
            name='request',
        ),
    ]
