from django.contrib import admin
from django.urls import path, include

from myapp import views

urlpatterns = [
    path('logout',views.logout,name='logout'),
    path('home',views.home,name='home'),
    path('',views.login,name='login'),
    path('login_post',views.login_post,name='login_post'),
    path('admin_home',views.admin_home,name='admin_home'),
    path('admin_manage_ert',views.admin_manage_ert,name="admin_manage_ert"),
    path('admin_camp_registration',views.admin_camp_registration,name='admin_camp_registration'),
    path('admin_add_new_notification',views.admin_add_new_notification,name='admin_add_new_notification'),
    path('admin_add_guideline',views.admin_add_guideline,name='admin_add_guideline'),
    path('admin_complaint_reply_send/<rid>',views.admin_complaint_reply_send,name='admin_complaint_reply_send'),
    path('admin_view_coordinator',views.admin_view_coordinator,name='admin_view_coordinator'),
    path('admin_add_camp',views.admin_add_camp,name='admin_add_camp'),
    path('admin_add_camp_post',views.admin_add_camp_post,name='admin_add_camp_post'),
    path('admin_edit_camp/<cid>',views.admin_edit_camp,name='admin_edit_camp'),
    path('admin_edit_camp_post',views.admin_edit_camp_post,name='admin_edit_camp_post'),
    path('admin_delete_camp/<cid>',views.admin_delete_camp,name='admin_delete_camp'),
    path('admin_view_complaint',views.admin_view_complaint,name='admin_view_complaint'),
    path('admin_add_coordinator',views.admin_add_coordinator,name='admin_add_coordinator'),
    path('admin_add_coordinator_post',views.admin_add_coordinator_post,name='admin_add_coordinator_post'),
    path('admin_edit_coordinator/<cid>',views.admin_edit_coordinator,name='admin_edit_coordinator'),
    path('admin_edit_coordinator_post',views.admin_edit_coordinator_post,name='admin_edit_coordinator_post'),
    path('admin_delete_coordinator/<lid>', views.admin_delete_coordinator, name='admin_delete_coordinator'),
    path('admin_add_guideline_post', views.admin_add_guideline_post, name='admin_add_guideline_post'),
    path('admin_view_guideline', views.admin_view_guideline, name='admin_view_guideline'),
    path('admin_delete_guideline/<gid>', views.admin_delete_guideline, name='admin_delete_guideline'),
    path('admin_accept_ert/<eid>', views.admin_accept_ert, name='admin_accept_ert'),
    path('admin_add_notification_post', views.admin_add_notification_post, name='admin_add_notification_post'),
    path('admin_complaint_reply_send_post', views.admin_complaint_reply_send_post, name='admin_complaint_reply_send_post'),
    path('admin_delete_complaint/<did>', views.admin_delete_complaint, name='admin_delete_complaint'),
    path('camp_search', views.camp_search, name='camp_search'),
    path('coordinator_home', views.coordinator_home, name='coordinator_home'),
    path('admin_view_notification', views.admin_view_notification, name='admin_view_notification'),
    path('admin_reject_ert/<eid>', views.admin_reject_ert, name='admin_reject_ert'),
    path('coordinator_change_password', views.coordinator_change_password, name='coordinator_change_password'),
    path('coordinator_change_password_post', views.coordinator_change_password_post, name='coordinator_change_password_post'),
    path('cordinator_manage_volunteer', views.cordinator_manage_volunteer, name='cordinator_manage_volunteer'),
    path('coordinator_add_volunteer', views.coordinator_add_volunteer, name='coordinator_add_volunteer'),
    path('coordinator_add_volunteer_post', views.coordinator_add_volunteer_post, name='coordinator_add_volunteer_post'),
    path('coor_delete_volu/<id>', views.coor_delete_volu, name='coor_delete_volu'),
    path('edit_volunteer/<id>', views.edit_volunteer, name='edit_volunteer'),
    path('edit_volunteer_post', views.edit_volunteer_post, name='edit_volunteer_post'),

    path('coordinator_stock_manage', views.coordinator_stock_manage, name='coordinator_stock_manage'),
    path('add_needs/<id>', views.add_needs, name='add_needs'),
    path('add_needs_post', views.add_needs_post, name='add_needs_post'),
    path('view_needs', views.view_needs, name='view_needs'),

    path('coordinator_add_stock', views.coordinator_add_stock, name='coordinator_add_stock'),
    path('coordinator_add_stock_post', views.coordinator_add_stock_post, name='coordinator_add_stock_post'),
    path('coordinator_delete_stock/<id>', views.coordinator_delete_stock, name='coordinator_delete_stock'),
    path('coordinator_edit_stock/<id>', views.coordinator_edit_stock, name='coordinator_edit_stock'),
    path('coordinator_edit_stock_post', views.coordinator_edit_stock_post, name='coordinator_edit_stock_post'),
    path('add_medical_support', views.add_medical_support, name='add_medical_support'),
    path('view_medi_support', views.view_medi_support, name='view_medi_support'),

    path('view_guidellines', views.view_guidellines, name='view_guidellines'),
    path('add_guideline', views.add_guideline, name='add_guideline'),
    path('delete_med/<id>', views.delete_med, name='delete_med'),
    path('delete_guidline/<id>', views.delete_guidline, name='delete_guidline'),



    path('emergency_reg', views.emergency_reg, name='emergency_reg'),
    path('emergency_home', views.emergency_home, name='emergency_home'),
    path('emergency_change_password', views.emergency_change_password, name='emergency_change_password'),
    path('emergency_view_request', views.emergency_view_request, name='emergency_view_request'),
    path('update_status_post', views.update_status_post, name='update_status_post'),
    path('update_status/<id>', views.update_status, name='update_status'),

    path('android_login', views.android_login, name='android_login'),
    path('user_reg', views.user_reg, name='user_reg'),
    path('user_change_password', views.user_change_password, name='user_change_password'),
    path('send_complaint', views.send_complaint, name='send_complaint'),
    path('user_view_reply', views.user_view_reply, name='user_view_reply'),
    path('add_item', views.add_item, name='add_item'),
    path('view_missing_item', views.view_missing_item, name='view_missing_item'),
    path('delete_item', views.delete_item, name='delete_item'),
    path('user_view_nearest_camp', views.user_view_nearest_camp, name='user_view_nearest_camp'),
    path('user_view_emergency', views.user_view_emergency, name='user_view_emergency'),
    path('user_send_request', views.user_send_request, name='user_send_request'),
    path('user_view_needs', views.user_view_needs, name='user_view_needs'),
    path('user_donate', views.user_donate, name='user_donate'),


    path('volounteer_reg', views.volounteer_reg, name='volounteer_reg'),
    path('volounteer_change_password', views.volounteer_change_password, name='volounteer_change_password'),
    path('v_view_needs', views.v_view_needs, name='v_view_needs'),
    path('v_add_services', views.v_add_services, name='v_add_services'),
    path('v_view_services', views.v_view_services, name='v_view_services'),
    path('delete_service', views.delete_service, name='delete_service'),
    path('v_view_goods', views.v_view_goods, name='v_view_goods'),
    path('update_goods', views.update_goods, name='update_goods'),
    path('v_view_medical_support', views.v_view_medical_support, name='v_view_medical_support'),
    path('update_medical_support', views.update_medical_support, name='update_medical_support'),
    path('v_add_item', views.v_add_item, name='v_add_item'),
    path('v_view_missing_item', views.v_view_missing_item, name='v_view_missing_item'),


    path('get_weather', views.get_weather, name='get_weather'),
    path('haversine', views.haversine, name='haversine'),

    path('map_start', views.map_start, name='map_start'),
    path('get_predict', views.get_predict, name='get_predict'),

]